# ===================================================
# DEVELOPMENT PROFILE
# ===================================================

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/work_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rahul123

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
jwt.secret=MySuperSecretKeyForWorkManagement2026DefaultKey32Bytes

# ===============================
# Gemini
# ===============================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# ===============================
# Logging
# ===============================
logging.level.com.Workmanagement=DEBUG
logging.level.org.springframework.security=INFO

# ===============================
# Actuator
# ===============================
management.endpoint.health.show-details=always

# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# ===============================
# CORS
# ===============================
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# ===============================
# Cookies
# ===============================
cookie.secure=false
cookie.same-site=Lax