package com.Workmanagement.audit.entity;

public enum AuditAction {

    USER_REGISTERED,
    USER_LOGIN,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_DELETED,

    REQUIREMENT_CREATED,
    REQUIREMENT_UPDATED,
    REQUIREMENT_DELETED,

    SUBMISSION_CREATED,
    SUBMISSION_STATUS_CHANGED,
    SUBMISSION_APPROVED,
    SUBMISSION_CHANGES_REQUESTED,
    SUBMISSION_RESUBMITTED,

    AI_EVALUATION_CREATED,
    AI_EVALUATION_COMPLETED,
    AI_EVALUATION_UPDATED,

    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    NOTIFICATION_CREATED,
    ANALYTICS_REPORT_EXPORTED,

    GENERAL
}
