package com.Workmanagement.audit.entity;

public enum AuditAction {

    TASK_CREATED,
    TASK_ASSIGNED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_DELETED,
    TASK_COMPLETED,

    SUBMISSION_CREATED,
    SUBMISSION_RESUBMITTED,
    SUBMISSION_APPROVED,
    CHANGES_REQUESTED,

    AI_EVALUATION_CREATED,
    AI_EVALUATION_FAILED,

    USER_REGISTERED
}
